<?php

declare(strict_types=1);

namespace NeuroSYS;

/**
 * Generated by tools/build-assets.mjs — do not edit.
 *
 * Every built asset the shell loads, as the URL the browser asks for, carrying a hash of the
 * content at that URL. {@link Layout} emits all three: the stylesheet, the entry script, and one
 * `<link rel="modulepreload">` per module so the graph is discovered in one round trip instead of
 * the wave-at-a-time walk an ES module tree is otherwise found by.
 *
 * The version is what lets `public/.htaccess` mark these `immutable` for a year. It is a hash of
 * the file's content *after* its own imports were stamped, so a change to a leaf module changes
 * every hash above it and none beside it.
 *
 * These are the versioned URLs. {@link Config}'s `SCRIPT` and `STYLESHEET` remain the canonical
 * unversioned paths — the fact about where the file lives, which is Config's business; this is the
 * fact about which copy of it, which is the build's. `ViewTest` pins that the two agree.
 *
 * Regenerate with `npm run build`. test/basic_test.sh rebuilds this file and diffs, so an edit
 * made here is lost at the next build and fails the verify script in the meantime — the same
 * arrangement as public/assets/css/style.css and public/assets/js/.
 */
final class AssetManifest
{
    /** The stylesheet, versioned. */
    public const string STYLESHEET = '/assets/css/v-5bad205e/style.css';

    /** The entry point — the only `<script>` the site loads — versioned. */
    public const string SCRIPT = '/assets/js/v-5bad205e/main.js';

    /** @var list<string> Every module the entry reaches, versioned, sorted, the entry excluded. */
    public const array MODULES = [
        '/assets/js/v-5bad205e/Config.js',
        '/assets/js/v-5bad205e/Navigation.js',
        '/assets/js/v-5bad205e/elements/CoverArt.js',
        '/assets/js/v-5bad205e/elements/NestedElement.js',
        '/assets/js/v-5bad205e/elements/arrangement/ArrangementSection.js',
        '/assets/js/v-5bad205e/elements/arrangement/ReleaseArrangement.js',
        '/assets/js/v-5bad205e/elements/download/DownloadCard.js',
        '/assets/js/v-5bad205e/elements/download/DownloadLabel.js',
        '/assets/js/v-5bad205e/elements/download/DownloadList.js',
        '/assets/js/v-5bad205e/elements/download/DownloadMeta.js',
        '/assets/js/v-5bad205e/elements/embed/ConsentGatedEmbed.js',
        '/assets/js/v-5bad205e/elements/embed/SoundCloudPlayer.js',
        '/assets/js/v-5bad205e/elements/embed/SoundCloudProfile.js',
        '/assets/js/v-5bad205e/elements/embed/SoundCloudWidget.js',
        '/assets/js/v-5bad205e/elements/release/ReleaseCard.js',
        '/assets/js/v-5bad205e/elements/release/ReleaseList.js',
        '/assets/js/v-5bad205e/elements/release/ReleaseMeta.js',
        '/assets/js/v-5bad205e/elements/release/ReleaseTitle.js',
        '/assets/js/v-5bad205e/elements/terminal/TerminalCommand.js',
        '/assets/js/v-5bad205e/elements/terminal/TerminalCursor.js',
        '/assets/js/v-5bad205e/elements/terminal/TerminalField.js',
        '/assets/js/v-5bad205e/elements/terminal/TerminalKey.js',
        '/assets/js/v-5bad205e/elements/terminal/TerminalValue.js',
        '/assets/js/v-5bad205e/elements/terminal/TerminalWindow.js',
        '/assets/js/v-5bad205e/elements/waveform/DemoWaveform.js',
        '/assets/js/v-5bad205e/model/CoverArtAttribute.js',
        '/assets/js/v-5bad205e/model/CssClass.js',
        '/assets/js/v-5bad205e/model/CustomProperty.js',
        '/assets/js/v-5bad205e/model/ElementId.js',
        '/assets/js/v-5bad205e/model/EmbedAttribute.js',
        '/assets/js/v-5bad205e/model/HtmlAttribute.js',
        '/assets/js/v-5bad205e/model/HtmlTag.js',
        '/assets/js/v-5bad205e/model/LinkAttribute.js',
        '/assets/js/v-5bad205e/model/Platform.js',
        '/assets/js/v-5bad205e/model/RequestHeader.js',
        '/assets/js/v-5bad205e/model/RequestedWith.js',
        '/assets/js/v-5bad205e/model/SoundCloudOption.js',
        '/assets/js/v-5bad205e/model/SoundCloudPlayerAttribute.js',
        '/assets/js/v-5bad205e/model/SoundCloudPlayerStyle.js',
        '/assets/js/v-5bad205e/model/Tag.js',
        '/assets/js/v-5bad205e/model/TerminalAttribute.js',
        '/assets/js/v-5bad205e/model/TerminalFieldAttribute.js',
        '/assets/js/v-5bad205e/model/TerminalFieldKey.js',
        '/assets/js/v-5bad205e/model/TerminalTone.js',
        '/assets/js/v-5bad205e/model/WaveformAttribute.js',
        '/assets/js/v-5bad205e/model/WaveformBand.js',
    ];
}
