<?php

declare(strict_types=1);

namespace NeuroSYS;

/**
 * Generated by phpanta/tools/build-assets.mjs — do not edit.
 *
 * Every built asset the shell loads, as the URL the browser asks for, carrying the build's stamp.
 * The site's shell emits all three: the stylesheet, the entry script, and one
 * `<link rel="modulepreload">` per module so the graph is discovered in one round trip instead of
 * the wave-at-a-time walk an ES module tree is otherwise found by.
 *
 * The stamp is what lets `public/.htaccess` mark these `immutable` for a year. It is one hash
 * over every module's URL and shipped bytes — or the bundle's — and the stylesheet's, so a change to
 * any of them changes every URL here.
 *
 * These are the versioned URLs: the fact about which copy of each file, which is the build's. Where
 * each file lives is the site's own business, and stays where the site states it.
 *
 * Regenerate by running that tool from the project's root. An edit made here is lost at the next
 * build — the same arrangement as public/assets/css/style.css and public/assets/js/.
 */
final class AssetManifest
{
    /** The stylesheet, versioned. */
    public const string STYLESHEET = '/assets/css/v-b621d849/style.css';

    /** The entry point — the only `<script>` the site loads — versioned. */
    public const string SCRIPT = '/assets/js/v-b621d849/main.js';

    /**
     * @var list<string> Every module the entry reaches, versioned, sorted, the entry excluded.
     *
     * **Empty when the graph shipped as one bundle**, which is the feature switching itself off
     * rather than a manifest that failed to generate. A preload hint flattens the wave-at-a-time
     * walk an ES module tree is discovered by; one file has no walk left to flatten.
     * The shell maps over this, so empty emits no links at all.
     */
    public const array MODULES = [
        '/assets/js/v-b621d849/Config.js',
        '/assets/js/v-b621d849/elements/CoverArt.js',
        '/assets/js/v-b621d849/elements/arrangement/ArrangementSection.js',
        '/assets/js/v-b621d849/elements/arrangement/ReleaseArrangement.js',
        '/assets/js/v-b621d849/elements/download/DownloadCard.js',
        '/assets/js/v-b621d849/elements/download/DownloadLabel.js',
        '/assets/js/v-b621d849/elements/download/DownloadList.js',
        '/assets/js/v-b621d849/elements/download/DownloadMeta.js',
        '/assets/js/v-b621d849/elements/embed/ConsentGatedEmbed.js',
        '/assets/js/v-b621d849/elements/embed/SoundCloudPlayer.js',
        '/assets/js/v-b621d849/elements/embed/SoundCloudProfile.js',
        '/assets/js/v-b621d849/elements/embed/SoundCloudWidget.js',
        '/assets/js/v-b621d849/elements/release/ReleaseCard.js',
        '/assets/js/v-b621d849/elements/release/ReleaseList.js',
        '/assets/js/v-b621d849/elements/release/ReleaseMeta.js',
        '/assets/js/v-b621d849/elements/release/ReleaseTitle.js',
        '/assets/js/v-b621d849/elements/terminal/TerminalCommand.js',
        '/assets/js/v-b621d849/elements/terminal/TerminalCursor.js',
        '/assets/js/v-b621d849/elements/terminal/TerminalField.js',
        '/assets/js/v-b621d849/elements/terminal/TerminalKey.js',
        '/assets/js/v-b621d849/elements/terminal/TerminalValue.js',
        '/assets/js/v-b621d849/elements/terminal/TerminalWindow.js',
        '/assets/js/v-b621d849/elements/waveform/DemoWaveform.js',
        '/assets/js/v-b621d849/model/CoverArtAttribute.js',
        '/assets/js/v-b621d849/model/CssClass.js',
        '/assets/js/v-b621d849/model/CustomProperty.js',
        '/assets/js/v-b621d849/model/EmbedAttribute.js',
        '/assets/js/v-b621d849/model/Platform.js',
        '/assets/js/v-b621d849/model/SoundCloudOption.js',
        '/assets/js/v-b621d849/model/SoundCloudPlayerAttribute.js',
        '/assets/js/v-b621d849/model/SoundCloudPlayerStyle.js',
        '/assets/js/v-b621d849/model/Tag.js',
        '/assets/js/v-b621d849/model/TerminalAttribute.js',
        '/assets/js/v-b621d849/model/TerminalFieldAttribute.js',
        '/assets/js/v-b621d849/model/TerminalFieldKey.js',
        '/assets/js/v-b621d849/model/TerminalTone.js',
        '/assets/js/v-b621d849/model/WaveformAttribute.js',
        '/assets/js/v-b621d849/model/WaveformBand.js',
        '/assets/js/v-b621d849/phpanta/Navigation.js',
        '/assets/js/v-b621d849/phpanta/Passkey.js',
        '/assets/js/v-b621d849/phpanta/elements/MachineFilter.js',
        '/assets/js/v-b621d849/phpanta/elements/MachineStats.js',
        '/assets/js/v-b621d849/phpanta/elements/NestedElement.js',
        '/assets/js/v-b621d849/phpanta/model/CeremonyType.js',
        '/assets/js/v-b621d849/phpanta/model/ElementId.js',
        '/assets/js/v-b621d849/phpanta/model/HtmlAttribute.js',
        '/assets/js/v-b621d849/phpanta/model/HtmlTag.js',
        '/assets/js/v-b621d849/phpanta/model/Language.js',
        '/assets/js/v-b621d849/phpanta/model/LinkAttribute.js',
        '/assets/js/v-b621d849/phpanta/model/MachineAttribute.js',
        '/assets/js/v-b621d849/phpanta/model/MachineCounter.js',
        '/assets/js/v-b621d849/phpanta/model/MachineReading.js',
        '/assets/js/v-b621d849/phpanta/model/MachineTag.js',
        '/assets/js/v-b621d849/phpanta/model/MediaType.js',
        '/assets/js/v-b621d849/phpanta/model/PasskeyAttribute.js',
        '/assets/js/v-b621d849/phpanta/model/PasskeyFormField.js',
        '/assets/js/v-b621d849/phpanta/model/RegionAttribute.js',
        '/assets/js/v-b621d849/phpanta/model/RequestHeader.js',
        '/assets/js/v-b621d849/phpanta/model/RequestedWith.js',
        '/assets/js/v-b621d849/phpanta/model/ResponseHeader.js',
        '/assets/js/v-b621d849/phpanta/model/ResultKey.js',
    ];
}
