<?php

declare(strict_types=1);

namespace NeuroSYS;

/**
 * Generated by tools/build-preload.mjs from public/assets/js/main.js — do not edit.
 *
 * Every module reachable from the entry point, as the URL the browser asks for. {@link Layout}
 * renders one `<link rel="modulepreload">` per entry so the graph is discovered in one round trip
 * instead of the wave-at-a-time walk an ES module tree is otherwise discovered by.
 *
 * Regenerate with `npm run build`. test/basic_test.sh rebuilds this file and diffs, so an edit
 * made here is lost at the next build and fails the verify script in the meantime — the same
 * arrangement as public/assets/css/style.css and public/assets/js/.
 *
 * The list is every module rather than the first wave, and main.js is deliberately absent: it is
 * the `<script src>` already being fetched. See the tool for both reasons.
 */
final class ModuleGraph
{
    /** @var list<string> Served URLs, sorted, main.js excluded. */
    public const array MODULES = [
        '/assets/js/Config.js',
        '/assets/js/Navigation.js',
        '/assets/js/elements/CoverArt.js',
        '/assets/js/elements/NestedElement.js',
        '/assets/js/elements/download/DownloadCard.js',
        '/assets/js/elements/download/DownloadLabel.js',
        '/assets/js/elements/download/DownloadList.js',
        '/assets/js/elements/download/DownloadMeta.js',
        '/assets/js/elements/embed/ConsentGatedEmbed.js',
        '/assets/js/elements/embed/SoundCloudPlayer.js',
        '/assets/js/elements/embed/SoundCloudProfile.js',
        '/assets/js/elements/embed/SoundCloudWidget.js',
        '/assets/js/elements/release/ReleaseCard.js',
        '/assets/js/elements/release/ReleaseList.js',
        '/assets/js/elements/release/ReleaseMeta.js',
        '/assets/js/elements/release/ReleaseTitle.js',
        '/assets/js/elements/terminal/TerminalCommand.js',
        '/assets/js/elements/terminal/TerminalCursor.js',
        '/assets/js/elements/terminal/TerminalField.js',
        '/assets/js/elements/terminal/TerminalKey.js',
        '/assets/js/elements/terminal/TerminalValue.js',
        '/assets/js/elements/terminal/TerminalWindow.js',
        '/assets/js/model/CoverArtAttribute.js',
        '/assets/js/model/CssClass.js',
        '/assets/js/model/CustomProperty.js',
        '/assets/js/model/ElementId.js',
        '/assets/js/model/EmbedAttribute.js',
        '/assets/js/model/HtmlAttribute.js',
        '/assets/js/model/HtmlTag.js',
        '/assets/js/model/LinkAttribute.js',
        '/assets/js/model/Platform.js',
        '/assets/js/model/RequestHeader.js',
        '/assets/js/model/RequestedWith.js',
        '/assets/js/model/SoundCloudOption.js',
        '/assets/js/model/SoundCloudPlayerAttribute.js',
        '/assets/js/model/SoundCloudPlayerStyle.js',
        '/assets/js/model/Tag.js',
        '/assets/js/model/TerminalAttribute.js',
        '/assets/js/model/TerminalFieldAttribute.js',
        '/assets/js/model/TerminalFieldKey.js',
        '/assets/js/model/TerminalTone.js',
    ];
}
